// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".
//
// HAND-MODIFIED FOR PATH Y VALIDATION — see metrics equivalent.

package internal

type LogsWrapper struct {
	h *Handle[ExportLogsServiceRequest]
}

func GetLogsOrig(ms LogsWrapper) *ExportLogsServiceRequest {
	return ms.h.orig
}

func GetLogsState(ms LogsWrapper) *State {
	return ms.h.state
}

func NewLogsWrapper(orig *ExportLogsServiceRequest, state *State) LogsWrapper {
	return LogsWrapper{h: &Handle[ExportLogsServiceRequest]{orig: orig, state: state}}
}

// DetachLogsIfShared — see DetachMetricsIfShared.
func DetachLogsIfShared(ms LogsWrapper) {
	DetachIfShared(ms.h, CopyExportLogsServiceRequest)
}

// GetLogsHandle — see GetMetricsHandle.
func GetLogsHandle(ms LogsWrapper) *Handle[ExportLogsServiceRequest] {
	return ms.h
}

func GenTestLogsWrapper() LogsWrapper {
	return NewLogsWrapper(GenTestExportLogsServiceRequest(), NewState())
}
