// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

type ProfilesWrapper struct {
	h *Handle[ExportProfilesServiceRequest]
}

func GetProfilesOrig(ms ProfilesWrapper) *ExportProfilesServiceRequest {
	return ms.h.GetOrig()
}

func GetProfilesState(ms ProfilesWrapper) *State {
	return ms.h.GetState()
}

func NewProfilesWrapper(orig *ExportProfilesServiceRequest, state *State) ProfilesWrapper {
	return ProfilesWrapper{h: NewHandle(orig, state)}
}

func GenTestProfilesWrapper() ProfilesWrapper {
	return NewProfilesWrapper(GenTestExportProfilesServiceRequest(), NewState())
}
