// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".
//
// HAND-MODIFIED FOR PATH Y VALIDATION (pdata.cow Alt A) — see the
// equivalent comment in generated_wrapper_exportmetricsservicerequest.go
// for the rationale. DO NOT regenerate until the pdatagen templates
// are updated to emit this layout.

package internal

type TracesWrapper struct {
	h *Handle[ExportTraceServiceRequest]
}

func GetTracesOrig(ms TracesWrapper) *ExportTraceServiceRequest {
	return ms.h.orig
}

func GetTracesState(ms TracesWrapper) *State {
	return ms.h.state
}

func NewTracesWrapper(orig *ExportTraceServiceRequest, state *State) TracesWrapper {
	return TracesWrapper{h: &Handle[ExportTraceServiceRequest]{orig: orig, state: state}}
}

// DetachTracesIfShared — see DetachMetricsIfShared.
func DetachTracesIfShared(ms TracesWrapper) {
	DetachIfShared(ms.h, CopyExportTraceServiceRequest)
}

// GetTracesHandle — see GetMetricsHandle.
func GetTracesHandle(ms TracesWrapper) *Handle[ExportTraceServiceRequest] {
	return ms.h
}

func GenTestTracesWrapper() TracesWrapper {
	return NewTracesWrapper(GenTestExportTraceServiceRequest(), NewState())
}
