// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".
//
// HAND-MODIFIED FOR PATH Y VALIDATION — see metrics equivalent.

package internal

type ProfilesWrapper struct {
	h *Handle[ExportProfilesServiceRequest]
}

func GetProfilesOrig(ms ProfilesWrapper) *ExportProfilesServiceRequest {
	return ms.h.orig
}

func GetProfilesState(ms ProfilesWrapper) *State {
	return ms.h.state
}

func NewProfilesWrapper(orig *ExportProfilesServiceRequest, state *State) ProfilesWrapper {
	return ProfilesWrapper{h: &Handle[ExportProfilesServiceRequest]{orig: orig, state: state}}
}

// DetachProfilesIfShared — see DetachMetricsIfShared.
func DetachProfilesIfShared(ms ProfilesWrapper) {
	DetachIfShared(ms.h, CopyExportProfilesServiceRequest)
}

// GetProfilesHandle — see GetMetricsHandle.
func GetProfilesHandle(ms ProfilesWrapper) *Handle[ExportProfilesServiceRequest] {
	return ms.h
}

func GenTestProfilesWrapper() ProfilesWrapper {
	return NewProfilesWrapper(GenTestExportProfilesServiceRequest(), NewState())
}
