// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

type LogsWrapper struct {
	h *Handle[ExportLogsServiceRequest]
}

func GetLogsOrig(ms LogsWrapper) *ExportLogsServiceRequest {
	return ms.h.GetOrig()
}

func GetLogsState(ms LogsWrapper) *State {
	return ms.h.GetState()
}

func NewLogsWrapper(orig *ExportLogsServiceRequest, state *State) LogsWrapper {
	return LogsWrapper{h: NewHandle(orig, state)}
}

func GenTestLogsWrapper() LogsWrapper {
	return NewLogsWrapper(GenTestExportLogsServiceRequest(), NewState())
}
