// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

type MetricsWrapper struct {
	h *Handle[ExportMetricsServiceRequest]
}

func GetMetricsOrig(ms MetricsWrapper) *ExportMetricsServiceRequest {
	return ms.h.GetOrig()
}

func GetMetricsState(ms MetricsWrapper) *State {
	return ms.h.GetState()
}

func NewMetricsWrapper(orig *ExportMetricsServiceRequest, state *State) MetricsWrapper {
	return MetricsWrapper{h: NewHandle(orig, state)}
}

func GenTestMetricsWrapper() MetricsWrapper {
	return NewMetricsWrapper(GenTestExportMetricsServiceRequest(), NewState())
}
