// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".
//
// HAND-MODIFIED FOR PATH Y VALIDATION (pdata.cow Alt A).
// Layout: {h *Handle[T]} instead of inline {orig, state}. The Handle
// indirection lets State.detachIfShared rebind orig + state in place
// when the wrapper's first mutating call fires on a shared backing
// tree. See pdata/internal/handle.go and perf/rfc/pdata-cow.md.
// pdatagen templates will be updated to emit this layout once the
// validation pass confirms the deferred-clone benefit at the pipeline
// level; until then this file is intentionally hand-modified — DO NOT
// regenerate or the manual edits will be lost.

package internal

type MetricsWrapper struct {
	h *Handle[ExportMetricsServiceRequest]
}

func GetMetricsOrig(ms MetricsWrapper) *ExportMetricsServiceRequest {
	return ms.h.orig
}

func GetMetricsState(ms MetricsWrapper) *State {
	return ms.h.state
}

func NewMetricsWrapper(orig *ExportMetricsServiceRequest, state *State) MetricsWrapper {
	return MetricsWrapper{h: &Handle[ExportMetricsServiceRequest]{orig: orig, state: state}}
}

// DetachMetricsIfShared is the typed Path-Y auto-detach entry point for
// the top-level Metrics wrapper. The codegen-injected prelude in every
// top-level mutating method (Metrics.MoveTo, Metrics.CopyTo, etc.)
// calls this before any actual mutation. Fast path (cowRefs == 0):
// one atomic load + compare, no allocation. Slow path: deep clone via
// CopyExportMetricsServiceRequest + Handle rebind. See detach.go.
//
// State-pristine design rationale: the per-signal closure can't live
// on *State because reflect.DeepEqual on two States with distinct
// closures (e.g. across a proto round-trip) reports unequal, breaking
// downstream wire-compatibility tests. Keeping the cloneFn embedded
// in this typed wrapper-package function instead leaves State as a
// pure value struct.
func DetachMetricsIfShared(ms MetricsWrapper) {
	DetachIfShared(ms.h, CopyExportMetricsServiceRequest)
}

// GetMetricsHandle returns the underlying Handle. Used by State.detach*
// helpers (and any future cow.* code) that need to rebind the wrapper's
// orig + state in place — value-typed wrappers can't rebind their own
// fields from a callee. Internal use only.
func GetMetricsHandle(ms MetricsWrapper) *Handle[ExportMetricsServiceRequest] {
	return ms.h
}

func GenTestMetricsWrapper() MetricsWrapper {
	return NewMetricsWrapper(GenTestExportMetricsServiceRequest(), NewState())
}
