// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package plog

import (
	"iter"
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
)

// ScopeLogsSlice logically represents a slice of ScopeLogs.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewScopeLogsSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-slice layout: carries the top-level Handle (shared with
// the parent tree) and the index path that locates this slice's
// position inside that tree. The slice's own elements are indexed by
// At()/AppendEmpty(); the indices the slice carries are its PARENT's
// indices (the slice IS a field on the parent struct).
type ScopeLogsSlice struct {
	h     *internal.Handle[internal.ExportLogsServiceRequest]
	rlIdx int
}

func newScopeLogsSlice(orig *[]*internal.ScopeLogs, state *internal.State) ScopeLogsSlice {
	// Path Y "always-h": synthesize a top-level parent tree whose target
	// slice IS the caller's orig (by pointer; not a copy). Mutations
	// through this wrapper propagate to *orig.
	return ScopeLogsSlice{
		h:     internal.NewHandle(&internal.ExportLogsServiceRequest{ResourceLogs: []*internal.ResourceLogs{{ScopeLogs: *orig}}}, state),
		rlIdx: 0,
	}
}

// NewScopeLogsSlice creates a ScopeLogsSliceWrapper with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewScopeLogsSlice() ScopeLogsSlice {
	orig := []*internal.ScopeLogs(nil)
	return newScopeLogsSlice(&orig, internal.NewState())
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewScopeLogsSlice()".
func (es ScopeLogsSlice) Len() int {
	return len(*es.getOrig())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ScopeLogsSlice) At(i int) ScopeLogs {
	// Tree-connected: element shares the slice's Handle + parent indices.
	// Direct struct literal avoids the standalone synthetic-Handle path
	// so cow.Share detach (Phase 5) can rebind the shared tree in place.
	return ScopeLogs{
		h:     es.h,
		rlIdx: es.rlIdx,
		slIdx: i,
	}
}

// All returns an iterator over index-value pairs in the slice.
//
//	for i, v := range es.All() {
//	    ... // Do something with index-value pair
//	}
func (es ScopeLogsSlice) All() iter.Seq2[int, ScopeLogs] {
	return func(yield func(int, ScopeLogs) bool) {
		for i := 0; i < es.Len(); i++ {
			if !yield(i, es.At(i)) {
				return
			}
		}
	}
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ScopeLogsSlice can be initialized:
//
//	es := NewScopeLogsSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ScopeLogsSlice) EnsureCapacity(newCap int) {
	// Path Y Phase 5 auto-detach prelude — see message.go.tmpl MoveTo.
	es.getState().DetachIfShared()
	es.getState().AssertMutable()
	oldCap := cap(*es.getOrig())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*internal.ScopeLogs, len(*es.getOrig()), newCap)
	copy(newOrig, *es.getOrig())
	*es.getOrig() = newOrig
}

// AppendEmpty will append to the end of the slice an empty ScopeLogs.
// It returns the newly added ScopeLogs.
func (es ScopeLogsSlice) AppendEmpty() ScopeLogs {
	es.getState().DetachIfShared()
	es.getState().AssertMutable()
	*es.getOrig() = append(*es.getOrig(), internal.NewScopeLogs())
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ScopeLogsSlice) MoveAndAppendTo(dest ScopeLogsSlice) {
	es.getState().DetachIfShared()
	dest.getState().DetachIfShared()
	es.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if es.getOrig() == dest.getOrig() {
		return
	}
	if *dest.getOrig() == nil {
		// We can simply move the entire vector and avoid any allocations.
		*dest.getOrig() = *es.getOrig()
	} else {
		*dest.getOrig() = append(*dest.getOrig(), *es.getOrig()...)
	}
	*es.getOrig() = nil
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ScopeLogsSlice) RemoveIf(f func(ScopeLogs) bool) {
	es.getState().DetachIfShared()
	es.getState().AssertMutable()
	newLen := 0
	for i := 0; i < len(*es.getOrig()); i++ {
		if f(es.At(i)) {
			internal.DeleteScopeLogs((*es.getOrig())[i], true)
			(*es.getOrig())[i] = nil

			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		(*es.getOrig())[newLen] = (*es.getOrig())[i]
		// Cannot delete here since we just move the data(or pointer to data) to a different position in the slice.
		(*es.getOrig())[i] = nil
		newLen++
	}
	*es.getOrig() = (*es.getOrig())[:newLen]
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ScopeLogsSlice) CopyTo(dest ScopeLogsSlice) {
	dest.getState().DetachIfShared()
	dest.getState().AssertMutable()
	if es.getOrig() == dest.getOrig() {
		return
	}
	*dest.getOrig() = internal.CopyScopeLogsPtrSlice(*dest.getOrig(), *es.getOrig())
}

// Sort sorts the ScopeLogs elements within ScopeLogsSlice given the
// provided less function so that two instances of ScopeLogsSlice
// can be compared.
func (es ScopeLogsSlice) Sort(less func(a, b ScopeLogs) bool) {
	es.getState().DetachIfShared()
	es.getState().AssertMutable()
	sort.SliceStable(*es.getOrig(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}

func (ms ScopeLogsSlice) getOrig() *[]*internal.ScopeLogs {
	return &ms.h.GetOrig().ResourceLogs[ms.rlIdx].ScopeLogs
}

func (ms ScopeLogsSlice) getState() *internal.State {
	return ms.h.GetState()
}
