// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package ptrace

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestScopeSpansSlice(t *testing.T) {
	es := NewScopeSpansSlice()
	assert.Equal(t, 0, es.Len())
	es = newScopeSpansSlice(&[]*internal.ScopeSpans{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewScopeSpans()
	testVal := generateTestScopeSpans()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl
		// for the full doc comment. Compare *getOrig() of the element so the
		// assertion survives the upcoming Handle-based wrapper layout.
		assert.Equal(t, *emptyVal.getOrig(), *es.At(i).getOrig())
		(*es.getOrig())[i] = internal.GenTestScopeSpans()
		assert.Equal(t, *testVal.getOrig(), *es.At(i).getOrig())
	}
	assert.Equal(t, 7, es.Len())
}

func TestScopeSpansSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newScopeSpansSlice(&[]*internal.ScopeSpans{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewScopeSpansSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestScopeSpansSlice_CopyTo(t *testing.T) {
	dest := NewScopeSpansSlice()
	src := generateTestScopeSpansSlice()
	src.CopyTo(dest)
	assert.Equal(t, *generateTestScopeSpansSlice().getOrig(), *dest.getOrig())
	dest.CopyTo(dest)
	assert.Equal(t, *generateTestScopeSpansSlice().getOrig(), *dest.getOrig())
}

func TestScopeSpansSlice_EnsureCapacity(t *testing.T) {
	es := generateTestScopeSpansSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.getOrig()))
	assert.Equal(t, *generateTestScopeSpansSlice().getOrig(), *es.getOrig())

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestScopeSpansSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.getOrig()))
	assert.Equal(t, *generateTestScopeSpansSlice().getOrig(), *es.getOrig())
}

func TestScopeSpansSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestScopeSpansSlice()
	dest := NewScopeSpansSlice()
	src := generateTestScopeSpansSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, *generateTestScopeSpansSlice().getOrig(), *dest.getOrig())
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, *generateTestScopeSpansSlice().getOrig(), *dest.getOrig())
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestScopeSpansSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i).getOrig())
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i + expectedSlice.Len()).getOrig())
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i).getOrig())
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i + expectedSlice.Len()).getOrig())
	}
}

func TestScopeSpansSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewScopeSpansSlice()
	emptySlice.RemoveIf(func(el ScopeSpans) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestScopeSpansSlice()
	pos := 0
	filtered.RemoveIf(func(el ScopeSpans) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestScopeSpansSlice_RemoveIfAll(t *testing.T) {
	got := generateTestScopeSpansSlice()
	got.RemoveIf(func(el ScopeSpans) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestScopeSpansSliceAll(t *testing.T) {
	ms := generateTestScopeSpansSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, *ms.At(i).getOrig(), *v.getOrig(), "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestScopeSpansSlice_Sort(t *testing.T) {
	es := generateTestScopeSpansSlice()
	es.Sort(func(a, b ScopeSpans) bool {
		return uintptr(unsafe.Pointer(a.getOrig())) < uintptr(unsafe.Pointer(b.getOrig()))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).getOrig())), uintptr(unsafe.Pointer(es.At(i).getOrig())))
	}
	es.Sort(func(a, b ScopeSpans) bool {
		return uintptr(unsafe.Pointer(a.getOrig())) > uintptr(unsafe.Pointer(b.getOrig()))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).getOrig())), uintptr(unsafe.Pointer(es.At(i).getOrig())))
	}
}

func generateTestScopeSpansSlice() ScopeSpansSlice {
	ms := NewScopeSpansSlice()
	*ms.getOrig() = internal.GenTestScopeSpansPtrSlice()
	return ms
}
