// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package ptrace

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// SpanEvent is a time-stamped annotation of the span, consisting of user-supplied
// text description and key-value pairs. See OTLP for event definition.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewSpanEvent function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-wrapper layout: carries a top-level Handle (shared with
// the parent tree under cow.Share*) and the index path that locates this
// type's orig inside that tree. getOrig() walks h.GetOrig() + indices.
// See perf/rfc/pdata-cow.md and internal/cmd/pdatagen/internal/pdata/nested_path.go.
type SpanEvent struct {
	h     *internal.Handle[internal.ExportTraceServiceRequest]
	rsIdx int
	ssIdx int
	sIdx  int
	eIdx  int
}

func newSpanEvent(orig *internal.SpanEvent, state *internal.State) SpanEvent {
	// Path Y "always-h" pattern: synthesize a single-element parent tree
	// wrapping orig so this standalone wrapper has the same struct shape
	// as a tree-embedded one. The synthetic tree contains orig by pointer
	// (not by copy), so mutations through this wrapper propagate to orig.
	return SpanEvent{
		h:     internal.NewHandle(&internal.ExportTraceServiceRequest{ResourceSpans: []*internal.ResourceSpans{{ScopeSpans: []*internal.ScopeSpans{{Spans: []*internal.Span{{Events: []*internal.SpanEvent{orig}}}}}}}}, state),
		rsIdx: 0,
		ssIdx: 0,
		sIdx:  0,
		eIdx:  0,
	}
}

// NewSpanEvent creates a new empty SpanEvent.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewSpanEvent() SpanEvent {
	return newSpanEvent(internal.NewSpanEvent(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms SpanEvent) MoveTo(dest SpanEvent) {
	// Path Y Phase 5 auto-detach prelude: if this wrapper is a cow.Share
	// (state.cowRefs > 0) and a detacher closure is installed, trigger
	// it before AssertMutable. The closure rebinds the top-level Handle
	// to a freshly-cloned tree so this mutation writes to a private
	// copy and leaves siblings/source untouched. Near-free fast path
	// (one atomic Load + branch) when not shared.
	ms.getState().DetachIfShared()
	dest.getState().DetachIfShared()
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteSpanEvent(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// Timestamp returns the timestamp associated with this SpanEvent.
func (ms SpanEvent) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.getOrig().TimeUnixNano)
}

// SetTimestamp replaces the timestamp associated with this SpanEvent.
func (ms SpanEvent) SetTimestamp(v pcommon.Timestamp) {
	ms.getState().AssertMutable()
	ms.getOrig().TimeUnixNano = uint64(v)
}

// Name returns the name associated with this SpanEvent.
func (ms SpanEvent) Name() string {
	return ms.getOrig().Name
}

// SetName replaces the name associated with this SpanEvent.
func (ms SpanEvent) SetName(v string) {
	ms.getState().AssertMutable()
	ms.getOrig().Name = v
}

// Attributes returns the Attributes associated with this SpanEvent.
func (ms SpanEvent) Attributes() pcommon.Map {
	return pcommon.Map(internal.NewMapWrapper(&ms.getOrig().Attributes, ms.getState()))
}

// DroppedAttributesCount returns the droppedattributescount associated with this SpanEvent.
func (ms SpanEvent) DroppedAttributesCount() uint32 {
	return ms.getOrig().DroppedAttributesCount
}

// SetDroppedAttributesCount replaces the droppedattributescount associated with this SpanEvent.
func (ms SpanEvent) SetDroppedAttributesCount(v uint32) {
	ms.getState().AssertMutable()
	ms.getOrig().DroppedAttributesCount = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms SpanEvent) CopyTo(dest SpanEvent) {
	// Path Y Phase 5 auto-detach prelude — see MoveTo for the doc.
	dest.getState().DetachIfShared()
	dest.getState().AssertMutable()
	internal.CopySpanEvent(dest.getOrig(), ms.getOrig())
}

func (ms SpanEvent) getOrig() *internal.SpanEvent {
	return ms.h.GetOrig().ResourceSpans[ms.rsIdx].ScopeSpans[ms.ssIdx].Spans[ms.sIdx].Events[ms.eIdx]
}

func (ms SpanEvent) getState() *internal.State {
	return ms.h.GetState()
}
