// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package ptrace

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceSpans is a collection of spans from a Resource.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResourceSpans function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-wrapper layout: carries a top-level Handle (shared with
// the parent tree under cow.Share*) and the index path that locates this
// type's orig inside that tree. getOrig() walks h.GetOrig() + indices.
// See perf/rfc/pdata-cow.md and internal/cmd/pdatagen/internal/pdata/nested_path.go.
type ResourceSpans struct {
	h     *internal.Handle[internal.ExportTraceServiceRequest]
	rsIdx int
}

func newResourceSpans(orig *internal.ResourceSpans, state *internal.State) ResourceSpans {
	// Path Y "always-h" pattern: synthesize a single-element parent tree
	// wrapping orig so this standalone wrapper has the same struct shape
	// as a tree-embedded one. The synthetic tree contains orig by pointer
	// (not by copy), so mutations through this wrapper propagate to orig.
	return ResourceSpans{
		h:     internal.NewHandle(&internal.ExportTraceServiceRequest{ResourceSpans: []*internal.ResourceSpans{orig}}, state),
		rsIdx: 0,
	}
}

// NewResourceSpans creates a new empty ResourceSpans.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResourceSpans() ResourceSpans {
	return newResourceSpans(internal.NewResourceSpans(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ResourceSpans) MoveTo(dest ResourceSpans) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteResourceSpans(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// Resource returns the resource associated with this ResourceSpans.
func (ms ResourceSpans) Resource() pcommon.Resource {
	return pcommon.Resource(internal.NewResourceWrapper(&ms.getOrig().Resource, ms.getState()))
}

// ScopeSpans returns the ScopeSpans associated with this ResourceSpans.
func (ms ResourceSpans) ScopeSpans() ScopeSpansSlice {
	return newScopeSpansSlice(&ms.getOrig().ScopeSpans, ms.getState())
}

// SchemaUrl returns the schemaurl associated with this ResourceSpans.
func (ms ResourceSpans) SchemaUrl() string {
	return ms.getOrig().SchemaUrl
}

// SetSchemaUrl replaces the schemaurl associated with this ResourceSpans.
func (ms ResourceSpans) SetSchemaUrl(v string) {
	ms.getState().AssertMutable()
	ms.getOrig().SchemaUrl = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ResourceSpans) CopyTo(dest ResourceSpans) {
	dest.getState().AssertMutable()
	internal.CopyResourceSpans(dest.getOrig(), ms.getOrig())
}

func (ms ResourceSpans) getOrig() *internal.ResourceSpans {
	return ms.h.GetOrig().ResourceSpans[ms.rsIdx]
}

func (ms ResourceSpans) getState() *internal.State {
	return ms.h.GetState()
}
