// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// Sample represents each record value encountered within a profiled program.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewSample function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-wrapper layout: carries a top-level Handle (shared with
// the parent tree under cow.Share*) and the index path that locates this
// type's orig inside that tree. getOrig() walks h.GetOrig() + indices.
// See perf/rfc/pdata-cow.md and internal/cmd/pdatagen/internal/pdata/nested_path.go.
type Sample struct {
	h     *internal.Handle[internal.ExportProfilesServiceRequest]
	rpIdx int
	spIdx int
	pIdx  int
	sIdx  int
}

func newSample(orig *internal.Sample, state *internal.State) Sample {
	// Path Y "always-h" pattern: synthesize a single-element parent tree
	// wrapping orig so this standalone wrapper has the same struct shape
	// as a tree-embedded one. The synthetic tree contains orig by pointer
	// (not by copy), so mutations through this wrapper propagate to orig.
	return Sample{
		h:     internal.NewHandle(&internal.ExportProfilesServiceRequest{ResourceProfiles: []*internal.ResourceProfiles{{ScopeProfiles: []*internal.ScopeProfiles{{Profiles: []*internal.Profile{{Samples: []*internal.Sample{orig}}}}}}}}, state),
		rpIdx: 0,
		spIdx: 0,
		pIdx:  0,
		sIdx:  0,
	}
}

// NewSample creates a new empty Sample.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewSample() Sample {
	return newSample(internal.NewSample(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Sample) MoveTo(dest Sample) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteSample(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// StackIndex returns the stackindex associated with this Sample.
func (ms Sample) StackIndex() int32 {
	return ms.getOrig().StackIndex
}

// SetStackIndex replaces the stackindex associated with this Sample.
func (ms Sample) SetStackIndex(v int32) {
	ms.getState().AssertMutable()
	ms.getOrig().StackIndex = v
}

// AttributeIndices returns the AttributeIndices associated with this Sample.
func (ms Sample) AttributeIndices() pcommon.Int32Slice {
	return pcommon.Int32Slice(internal.NewInt32SliceWrapper(&ms.getOrig().AttributeIndices, ms.getState()))
}

// LinkIndex returns the linkindex associated with this Sample.
func (ms Sample) LinkIndex() int32 {
	return ms.getOrig().LinkIndex
}

// SetLinkIndex replaces the linkindex associated with this Sample.
func (ms Sample) SetLinkIndex(v int32) {
	ms.getState().AssertMutable()
	ms.getOrig().LinkIndex = v
}

// Values returns the Values associated with this Sample.
func (ms Sample) Values() pcommon.Int64Slice {
	return pcommon.Int64Slice(internal.NewInt64SliceWrapper(&ms.getOrig().Values, ms.getState()))
}

// TimestampsUnixNano returns the TimestampsUnixNano associated with this Sample.
func (ms Sample) TimestampsUnixNano() pcommon.UInt64Slice {
	return pcommon.UInt64Slice(internal.NewUInt64SliceWrapper(&ms.getOrig().TimestampsUnixNano, ms.getState()))
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Sample) CopyTo(dest Sample) {
	dest.getState().AssertMutable()
	internal.CopySample(dest.getOrig(), ms.getOrig())
}

func (ms Sample) getOrig() *internal.Sample {
	return ms.h.GetOrig().ResourceProfiles[ms.rpIdx].ScopeProfiles[ms.spIdx].Profiles[ms.pIdx].Samples[ms.sIdx]
}

func (ms Sample) getState() *internal.State {
	return ms.h.GetState()
}
