// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestProfile_MoveTo(t *testing.T) {
	ms := generateTestProfile()
	dest := NewProfile()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewProfile().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestProfile().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestProfile().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newProfile(internal.NewProfile(), sharedState)) })
	assert.Panics(t, func() { newProfile(internal.NewProfile(), sharedState).MoveTo(dest) })
}

func TestProfile_CopyTo(t *testing.T) {
	ms := NewProfile()
	orig := NewProfile()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestProfile()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newProfile(internal.NewProfile(), sharedState)) })
}

func TestProfile_SampleType(t *testing.T) {
	ms := NewProfile()
	// Semantic equality (Path Y Phase 4 step 2a): compare *getOrig() rather
	// than the wrapper struct itself. See message_test.go.tmpl for rationale.
	// When the field type lives in a different package (.messageHasWrapper),
	// use the exported internal.Get<X>Orig accessor since getOrig() is
	// package-private. When it lives in the same package, use getOrig()
	// directly.
	assert.Equal(t, *NewValueType().getOrig(), *ms.SampleType().getOrig())
	ms.getOrig().SampleType = *internal.GenTestValueType()
	assert.Equal(t, *generateTestValueType().getOrig(), *ms.SampleType().getOrig())
}

func TestProfile_Samples(t *testing.T) {
	ms := NewProfile()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewSampleSlice().getOrig(), *ms.Samples().getOrig())
	ms.getOrig().Samples = internal.GenTestSamplePtrSlice()
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *ms.Samples().getOrig())
}

func TestProfile_Time(t *testing.T) {
	ms := NewProfile()
	assert.Equal(t, pcommon.Timestamp(0), ms.Time())
	testValTime := pcommon.Timestamp(1234567890)
	ms.SetTime(testValTime)
	assert.Equal(t, testValTime, ms.Time())
}

func TestProfile_DurationNano(t *testing.T) {
	ms := NewProfile()
	assert.Equal(t, uint64(0), ms.DurationNano())
	ms.SetDurationNano(uint64(13))
	assert.Equal(t, uint64(13), ms.DurationNano())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newProfile(internal.NewProfile(), sharedState).SetDurationNano(uint64(13)) })
}

func TestProfile_PeriodType(t *testing.T) {
	ms := NewProfile()
	// Semantic equality (Path Y Phase 4 step 2a): compare *getOrig() rather
	// than the wrapper struct itself. See message_test.go.tmpl for rationale.
	// When the field type lives in a different package (.messageHasWrapper),
	// use the exported internal.Get<X>Orig accessor since getOrig() is
	// package-private. When it lives in the same package, use getOrig()
	// directly.
	assert.Equal(t, *NewValueType().getOrig(), *ms.PeriodType().getOrig())
	ms.getOrig().PeriodType = *internal.GenTestValueType()
	assert.Equal(t, *generateTestValueType().getOrig(), *ms.PeriodType().getOrig())
}

func TestProfile_Period(t *testing.T) {
	ms := NewProfile()
	assert.Equal(t, int64(0), ms.Period())
	ms.SetPeriod(int64(13))
	assert.Equal(t, int64(13), ms.Period())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newProfile(internal.NewProfile(), sharedState).SetPeriod(int64(13)) })
}

func TestProfile_ProfileID(t *testing.T) {
	ms := NewProfile()
	assert.Equal(t, ProfileID(internal.ProfileID([16]byte{})), ms.ProfileID())
	testValProfileID := ProfileID(internal.ProfileID([16]byte{1, 2, 3, 4, 5, 6, 7, 8, 8, 7, 6, 5, 4, 3, 2, 1}))
	ms.SetProfileID(testValProfileID)
	assert.Equal(t, testValProfileID, ms.ProfileID())
}

func TestProfile_DroppedAttributesCount(t *testing.T) {
	ms := NewProfile()
	assert.Equal(t, uint32(0), ms.DroppedAttributesCount())
	ms.SetDroppedAttributesCount(uint32(13))
	assert.Equal(t, uint32(13), ms.DroppedAttributesCount())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newProfile(internal.NewProfile(), sharedState).SetDroppedAttributesCount(uint32(13)) })
}

func TestProfile_OriginalPayloadFormat(t *testing.T) {
	ms := NewProfile()
	assert.Empty(t, ms.OriginalPayloadFormat())
	ms.SetOriginalPayloadFormat("test_originalpayloadformat")
	assert.Equal(t, "test_originalpayloadformat", ms.OriginalPayloadFormat())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newProfile(internal.NewProfile(), sharedState).SetOriginalPayloadFormat("test_originalpayloadformat")
	})
}

func TestProfile_OriginalPayload(t *testing.T) {
	ms := NewProfile()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetByteSliceOrig(internal.ByteSliceWrapper(pcommon.NewByteSlice())), *internal.GetByteSliceOrig(internal.ByteSliceWrapper(ms.OriginalPayload())))
	ms.getOrig().OriginalPayload = internal.GenTestByteSlice()
	assert.Equal(t, *internal.GetByteSliceOrig(internal.GenTestByteSliceWrapper()), *internal.GetByteSliceOrig(internal.ByteSliceWrapper(ms.OriginalPayload())))
}

func TestProfile_AttributeIndices(t *testing.T) {
	ms := NewProfile()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetInt32SliceOrig(internal.Int32SliceWrapper(pcommon.NewInt32Slice())), *internal.GetInt32SliceOrig(internal.Int32SliceWrapper(ms.AttributeIndices())))
	ms.getOrig().AttributeIndices = internal.GenTestInt32Slice()
	assert.Equal(t, *internal.GetInt32SliceOrig(internal.GenTestInt32SliceWrapper()), *internal.GetInt32SliceOrig(internal.Int32SliceWrapper(ms.AttributeIndices())))
}

func generateTestProfile() Profile {
	return newProfile(internal.GenTestProfile(), internal.NewState())
}
