// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// Line details a specific line in a source code, linked to a function.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewLine function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Line struct {
	orig  *internal.Line
	state *internal.State
}

func newLine(orig *internal.Line, state *internal.State) Line {
	return Line{orig: orig, state: state}
}

// NewLine creates a new empty Line.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewLine() Line {
	return newLine(internal.NewLine(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Line) MoveTo(dest Line) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteLine(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// FunctionIndex returns the functionindex associated with this Line.
func (ms Line) FunctionIndex() int32 {
	return ms.getOrig().FunctionIndex
}

// SetFunctionIndex replaces the functionindex associated with this Line.
func (ms Line) SetFunctionIndex(v int32) {
	ms.getState().AssertMutable()
	ms.getOrig().FunctionIndex = v
}

// Line returns the line associated with this Line.
func (ms Line) Line() int64 {
	return ms.getOrig().Line
}

// SetLine replaces the line associated with this Line.
func (ms Line) SetLine(v int64) {
	ms.getState().AssertMutable()
	ms.getOrig().Line = v
}

// Column returns the column associated with this Line.
func (ms Line) Column() int64 {
	return ms.getOrig().Column
}

// SetColumn replaces the column associated with this Line.
func (ms Line) SetColumn(v int64) {
	ms.getState().AssertMutable()
	ms.getOrig().Column = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Line) CopyTo(dest Line) {
	dest.getState().AssertMutable()
	internal.CopyLine(dest.getOrig(), ms.getOrig())
}

func (ms Line) getOrig() *internal.Line {
	return ms.orig
}

func (ms Line) getState() *internal.State {
	return ms.state
}
