// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestResourceProfiles_MoveTo(t *testing.T) {
	ms := generateTestResourceProfiles()
	dest := NewResourceProfiles()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewResourceProfiles().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestResourceProfiles().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestResourceProfiles().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newResourceProfiles(internal.NewResourceProfiles(), sharedState)) })
	assert.Panics(t, func() { newResourceProfiles(internal.NewResourceProfiles(), sharedState).MoveTo(dest) })
}

func TestResourceProfiles_CopyTo(t *testing.T) {
	ms := NewResourceProfiles()
	orig := NewResourceProfiles()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestResourceProfiles()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newResourceProfiles(internal.NewResourceProfiles(), sharedState)) })
}

func TestResourceProfiles_Resource(t *testing.T) {
	ms := NewResourceProfiles()
	// Semantic equality (Path Y Phase 4 step 2a): compare *getOrig() rather
	// than the wrapper struct itself. See message_test.go.tmpl for rationale.
	// When the field type lives in a different package (.messageHasWrapper),
	// use the exported internal.Get<X>Orig accessor since getOrig() is
	// package-private. When it lives in the same package, use getOrig()
	// directly.
	assert.Equal(t, *internal.GetResourceOrig(internal.ResourceWrapper(pcommon.NewResource())), *internal.GetResourceOrig(internal.ResourceWrapper(ms.Resource())))
	ms.getOrig().Resource = *internal.GenTestResource()
	assert.Equal(t, *internal.GetResourceOrig(internal.GenTestResourceWrapper()), *internal.GetResourceOrig(internal.ResourceWrapper(ms.Resource())))
}

func TestResourceProfiles_ScopeProfiles(t *testing.T) {
	ms := NewResourceProfiles()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewScopeProfilesSlice().getOrig(), *ms.ScopeProfiles().getOrig())
	ms.getOrig().ScopeProfiles = internal.GenTestScopeProfilesPtrSlice()
	assert.Equal(t, *generateTestScopeProfilesSlice().getOrig(), *ms.ScopeProfiles().getOrig())
}

func TestResourceProfiles_SchemaUrl(t *testing.T) {
	ms := NewResourceProfiles()
	assert.Empty(t, ms.SchemaUrl())
	ms.SetSchemaUrl("test_schemaurl")
	assert.Equal(t, "test_schemaurl", ms.SchemaUrl())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newResourceProfiles(internal.NewResourceProfiles(), sharedState).SetSchemaUrl("test_schemaurl")
	})
}

func generateTestResourceProfiles() ResourceProfiles {
	return newResourceProfiles(internal.GenTestResourceProfiles(), internal.NewState())
}
