// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestProfilesDictionary_MoveTo(t *testing.T) {
	ms := generateTestProfilesDictionary()
	dest := NewProfilesDictionary()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewProfilesDictionary().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestProfilesDictionary().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestProfilesDictionary().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newProfilesDictionary(internal.NewProfilesDictionary(), sharedState)) })
	assert.Panics(t, func() { newProfilesDictionary(internal.NewProfilesDictionary(), sharedState).MoveTo(dest) })
}

func TestProfilesDictionary_CopyTo(t *testing.T) {
	ms := NewProfilesDictionary()
	orig := NewProfilesDictionary()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestProfilesDictionary()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newProfilesDictionary(internal.NewProfilesDictionary(), sharedState)) })
}

func TestProfilesDictionary_MappingTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewMappingSlice().getOrig(), *ms.MappingTable().getOrig())
	ms.getOrig().MappingTable = internal.GenTestMappingPtrSlice()
	assert.Equal(t, *generateTestMappingSlice().getOrig(), *ms.MappingTable().getOrig())
}

func TestProfilesDictionary_LocationTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewLocationSlice().getOrig(), *ms.LocationTable().getOrig())
	ms.getOrig().LocationTable = internal.GenTestLocationPtrSlice()
	assert.Equal(t, *generateTestLocationSlice().getOrig(), *ms.LocationTable().getOrig())
}

func TestProfilesDictionary_FunctionTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewFunctionSlice().getOrig(), *ms.FunctionTable().getOrig())
	ms.getOrig().FunctionTable = internal.GenTestFunctionPtrSlice()
	assert.Equal(t, *generateTestFunctionSlice().getOrig(), *ms.FunctionTable().getOrig())
}

func TestProfilesDictionary_LinkTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewLinkSlice().getOrig(), *ms.LinkTable().getOrig())
	ms.getOrig().LinkTable = internal.GenTestLinkPtrSlice()
	assert.Equal(t, *generateTestLinkSlice().getOrig(), *ms.LinkTable().getOrig())
}

func TestProfilesDictionary_StringTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetStringSliceOrig(internal.StringSliceWrapper(pcommon.NewStringSlice())), *internal.GetStringSliceOrig(internal.StringSliceWrapper(ms.StringTable())))
	ms.getOrig().StringTable = internal.GenTestStringSlice()
	assert.Equal(t, *internal.GetStringSliceOrig(internal.GenTestStringSliceWrapper()), *internal.GetStringSliceOrig(internal.StringSliceWrapper(ms.StringTable())))
}

func TestProfilesDictionary_AttributeTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewKeyValueAndUnitSlice().getOrig(), *ms.AttributeTable().getOrig())
	ms.getOrig().AttributeTable = internal.GenTestKeyValueAndUnitPtrSlice()
	assert.Equal(t, *generateTestKeyValueAndUnitSlice().getOrig(), *ms.AttributeTable().getOrig())
}

func TestProfilesDictionary_StackTable(t *testing.T) {
	ms := NewProfilesDictionary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewStackSlice().getOrig(), *ms.StackTable().getOrig())
	ms.getOrig().StackTable = internal.GenTestStackPtrSlice()
	assert.Equal(t, *generateTestStackSlice().getOrig(), *ms.StackTable().getOrig())
}

func generateTestProfilesDictionary() ProfilesDictionary {
	return newProfilesDictionary(internal.GenTestProfilesDictionary(), internal.NewState())
}
