// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestSampleSlice(t *testing.T) {
	es := NewSampleSlice()
	assert.Equal(t, 0, es.Len())
	es = newSampleSlice(&[]*internal.Sample{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewSample()
	testVal := generateTestSample()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl
		// for the full doc comment. Compare *getOrig() of the element so the
		// assertion survives the upcoming Handle-based wrapper layout.
		assert.Equal(t, *emptyVal.getOrig(), *es.At(i).getOrig())
		(*es.getOrig())[i] = internal.GenTestSample()
		assert.Equal(t, *testVal.getOrig(), *es.At(i).getOrig())
	}
	assert.Equal(t, 7, es.Len())
}

func TestSampleSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newSampleSlice(&[]*internal.Sample{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewSampleSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestSampleSlice_CopyTo(t *testing.T) {
	dest := NewSampleSlice()
	src := generateTestSampleSlice()
	src.CopyTo(dest)
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *dest.getOrig())
	dest.CopyTo(dest)
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *dest.getOrig())
}

func TestSampleSlice_EnsureCapacity(t *testing.T) {
	es := generateTestSampleSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.getOrig()))
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *es.getOrig())

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestSampleSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.getOrig()))
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *es.getOrig())
}

func TestSampleSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestSampleSlice()
	dest := NewSampleSlice()
	src := generateTestSampleSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *dest.getOrig())
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, *generateTestSampleSlice().getOrig(), *dest.getOrig())
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestSampleSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i).getOrig())
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i + expectedSlice.Len()).getOrig())
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i).getOrig())
		assert.Equal(t, *expectedSlice.At(i).getOrig(), *dest.At(i + expectedSlice.Len()).getOrig())
	}
}

func TestSampleSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewSampleSlice()
	emptySlice.RemoveIf(func(el Sample) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestSampleSlice()
	pos := 0
	filtered.RemoveIf(func(el Sample) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestSampleSlice_RemoveIfAll(t *testing.T) {
	got := generateTestSampleSlice()
	got.RemoveIf(func(el Sample) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestSampleSliceAll(t *testing.T) {
	ms := generateTestSampleSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, *ms.At(i).getOrig(), *v.getOrig(), "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestSampleSlice_Sort(t *testing.T) {
	es := generateTestSampleSlice()
	es.Sort(func(a, b Sample) bool {
		return uintptr(unsafe.Pointer(a.getOrig())) < uintptr(unsafe.Pointer(b.getOrig()))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).getOrig())), uintptr(unsafe.Pointer(es.At(i).getOrig())))
	}
	es.Sort(func(a, b Sample) bool {
		return uintptr(unsafe.Pointer(a.getOrig())) > uintptr(unsafe.Pointer(b.getOrig()))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).getOrig())), uintptr(unsafe.Pointer(es.At(i).getOrig())))
	}
}

func generateTestSampleSlice() SampleSlice {
	ms := NewSampleSlice()
	*ms.getOrig() = internal.GenTestSamplePtrSlice()
	return ms
}
