// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"iter"
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
)

// ProfilesSlice logically represents a slice of Profile.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewProfilesSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-slice layout: carries the top-level Handle (shared with
// the parent tree) and the index path that locates this slice's
// position inside that tree. The slice's own elements are indexed by
// At()/AppendEmpty(); the indices the slice carries are its PARENT's
// indices (the slice IS a field on the parent struct).
type ProfilesSlice struct {
	h     *internal.Handle[internal.ExportProfilesServiceRequest]
	rpIdx int
	spIdx int
}

func newProfilesSlice(orig *[]*internal.Profile, state *internal.State) ProfilesSlice {
	// Path Y "always-h": synthesize a top-level parent tree whose target
	// slice IS the caller's orig (by pointer; not a copy). Mutations
	// through this wrapper propagate to *orig.
	return ProfilesSlice{
		h:     internal.NewHandle(&internal.ExportProfilesServiceRequest{ResourceProfiles: []*internal.ResourceProfiles{{ScopeProfiles: []*internal.ScopeProfiles{{Profiles: *orig}}}}}, state),
		rpIdx: 0,
		spIdx: 0,
	}
}

// NewProfilesSlice creates a ProfilesSliceWrapper with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewProfilesSlice() ProfilesSlice {
	orig := []*internal.Profile(nil)
	return newProfilesSlice(&orig, internal.NewState())
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewProfilesSlice()".
func (es ProfilesSlice) Len() int {
	return len(*es.getOrig())
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es ProfilesSlice) At(i int) Profile {
	// Tree-connected: element shares the slice's Handle + parent indices.
	// Direct struct literal avoids the standalone synthetic-Handle path
	// so cow.Share detach (Phase 5) can rebind the shared tree in place.
	return Profile{
		h:     es.h,
		rpIdx: es.rpIdx,
		spIdx: es.spIdx,
		pIdx:  i,
	}
}

// All returns an iterator over index-value pairs in the slice.
//
//	for i, v := range es.All() {
//	    ... // Do something with index-value pair
//	}
func (es ProfilesSlice) All() iter.Seq2[int, Profile] {
	return func(yield func(int, Profile) bool) {
		for i := 0; i < es.Len(); i++ {
			if !yield(i, es.At(i)) {
				return
			}
		}
	}
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ProfilesSlice can be initialized:
//
//	es := NewProfilesSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es ProfilesSlice) EnsureCapacity(newCap int) {
	es.getState().AssertMutable()
	oldCap := cap(*es.getOrig())
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*internal.Profile, len(*es.getOrig()), newCap)
	copy(newOrig, *es.getOrig())
	*es.getOrig() = newOrig
}

// AppendEmpty will append to the end of the slice an empty Profile.
// It returns the newly added Profile.
func (es ProfilesSlice) AppendEmpty() Profile {
	es.getState().AssertMutable()
	*es.getOrig() = append(*es.getOrig(), internal.NewProfile())
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ProfilesSlice) MoveAndAppendTo(dest ProfilesSlice) {
	es.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if es.getOrig() == dest.getOrig() {
		return
	}
	if *dest.getOrig() == nil {
		// We can simply move the entire vector and avoid any allocations.
		*dest.getOrig() = *es.getOrig()
	} else {
		*dest.getOrig() = append(*dest.getOrig(), *es.getOrig()...)
	}
	*es.getOrig() = nil
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ProfilesSlice) RemoveIf(f func(Profile) bool) {
	es.getState().AssertMutable()
	newLen := 0
	for i := 0; i < len(*es.getOrig()); i++ {
		if f(es.At(i)) {
			internal.DeleteProfile((*es.getOrig())[i], true)
			(*es.getOrig())[i] = nil

			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		(*es.getOrig())[newLen] = (*es.getOrig())[i]
		// Cannot delete here since we just move the data(or pointer to data) to a different position in the slice.
		(*es.getOrig())[i] = nil
		newLen++
	}
	*es.getOrig() = (*es.getOrig())[:newLen]
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es ProfilesSlice) CopyTo(dest ProfilesSlice) {
	dest.getState().AssertMutable()
	if es.getOrig() == dest.getOrig() {
		return
	}
	*dest.getOrig() = internal.CopyProfilePtrSlice(*dest.getOrig(), *es.getOrig())
}

// Sort sorts the Profile elements within ProfilesSlice given the
// provided less function so that two instances of ProfilesSlice
// can be compared.
func (es ProfilesSlice) Sort(less func(a, b Profile) bool) {
	es.getState().AssertMutable()
	sort.SliceStable(*es.getOrig(), func(i, j int) bool { return less(es.At(i), es.At(j)) })
}

func (ms ProfilesSlice) getOrig() *[]*internal.Profile {
	return &ms.h.GetOrig().ResourceProfiles[ms.rpIdx].ScopeProfiles[ms.spIdx].Profiles
}

func (ms ProfilesSlice) getState() *internal.State {
	return ms.h.GetState()
}
