// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ScopeProfiles is a collection of profiles from a LibraryInstrumentation.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewScopeProfiles function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-wrapper layout: carries a top-level Handle (shared with
// the parent tree under cow.Share*) and the index path that locates this
// type's orig inside that tree. getOrig() walks h.GetOrig() + indices.
// See perf/rfc/pdata-cow.md and internal/cmd/pdatagen/internal/pdata/nested_path.go.
type ScopeProfiles struct {
	h     *internal.Handle[internal.ExportProfilesServiceRequest]
	rpIdx int
	spIdx int
}

func newScopeProfiles(orig *internal.ScopeProfiles, state *internal.State) ScopeProfiles {
	// Path Y "always-h" pattern: synthesize a single-element parent tree
	// wrapping orig so this standalone wrapper has the same struct shape
	// as a tree-embedded one. The synthetic tree contains orig by pointer
	// (not by copy), so mutations through this wrapper propagate to orig.
	return ScopeProfiles{
		h:     internal.NewHandle(&internal.ExportProfilesServiceRequest{ResourceProfiles: []*internal.ResourceProfiles{{ScopeProfiles: []*internal.ScopeProfiles{orig}}}}, state),
		rpIdx: 0,
		spIdx: 0,
	}
}

// NewScopeProfiles creates a new empty ScopeProfiles.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewScopeProfiles() ScopeProfiles {
	return newScopeProfiles(internal.NewScopeProfiles(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ScopeProfiles) MoveTo(dest ScopeProfiles) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteScopeProfiles(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// Scope returns the scope associated with this ScopeProfiles.
func (ms ScopeProfiles) Scope() pcommon.InstrumentationScope {
	return pcommon.InstrumentationScope(internal.NewInstrumentationScopeWrapper(&ms.getOrig().Scope, ms.getState()))
}

// Profiles returns the Profiles associated with this ScopeProfiles.
func (ms ScopeProfiles) Profiles() ProfilesSlice {
	// Tree-connected (nested parent): slice shares ms's Handle + indices
	// so cow.Share detach (Phase 5) rebinds the shared tree in place
	// across parent and all derived slice/element wrappers.
	return ProfilesSlice{
		h:     ms.h,
		rpIdx: ms.rpIdx,
		spIdx: ms.spIdx,
	}
}

// SchemaUrl returns the schemaurl associated with this ScopeProfiles.
func (ms ScopeProfiles) SchemaUrl() string {
	return ms.getOrig().SchemaUrl
}

// SetSchemaUrl replaces the schemaurl associated with this ScopeProfiles.
func (ms ScopeProfiles) SetSchemaUrl(v string) {
	ms.getState().AssertMutable()
	ms.getOrig().SchemaUrl = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ScopeProfiles) CopyTo(dest ScopeProfiles) {
	dest.getState().AssertMutable()
	internal.CopyScopeProfiles(dest.getOrig(), ms.getOrig())
}

func (ms ScopeProfiles) getOrig() *internal.ScopeProfiles {
	return ms.h.GetOrig().ResourceProfiles[ms.rpIdx].ScopeProfiles[ms.spIdx]
}

func (ms ScopeProfiles) getState() *internal.State {
	return ms.h.GetState()
}
