// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceProfiles is a collection of profiles from a Resource.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResourceProfiles function to create new instances.
// Important: zero-initialized instance is not valid for use.
// Path Y nested-wrapper layout: carries a top-level Handle (shared with
// the parent tree under cow.Share*) and the index path that locates this
// type's orig inside that tree. getOrig() walks h.GetOrig() + indices.
// See perf/rfc/pdata-cow.md and internal/cmd/pdatagen/internal/pdata/nested_path.go.
type ResourceProfiles struct {
	h     *internal.Handle[internal.ExportProfilesServiceRequest]
	rpIdx int
}

func newResourceProfiles(orig *internal.ResourceProfiles, state *internal.State) ResourceProfiles {
	// Path Y "always-h" pattern: synthesize a single-element parent tree
	// wrapping orig so this standalone wrapper has the same struct shape
	// as a tree-embedded one. The synthetic tree contains orig by pointer
	// (not by copy), so mutations through this wrapper propagate to orig.
	return ResourceProfiles{
		h:     internal.NewHandle(&internal.ExportProfilesServiceRequest{ResourceProfiles: []*internal.ResourceProfiles{orig}}, state),
		rpIdx: 0,
	}
}

// NewResourceProfiles creates a new empty ResourceProfiles.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResourceProfiles() ResourceProfiles {
	return newResourceProfiles(internal.NewResourceProfiles(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ResourceProfiles) MoveTo(dest ResourceProfiles) {
	// Path Y Phase 5 auto-detach prelude: if this wrapper is a cow.Share
	// (state.cowRefs > 0) and a detacher closure is installed, trigger
	// it before AssertMutable. The closure rebinds the top-level Handle
	// to a freshly-cloned tree so this mutation writes to a private
	// copy and leaves siblings/source untouched. Near-free fast path
	// (one atomic Load + branch) when not shared.
	ms.getState().DetachIfShared()
	dest.getState().DetachIfShared()
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteResourceProfiles(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// Resource returns the resource associated with this ResourceProfiles.
func (ms ResourceProfiles) Resource() pcommon.Resource {
	return pcommon.Resource(internal.NewResourceWrapper(&ms.getOrig().Resource, ms.getState()))
}

// ScopeProfiles returns the ScopeProfiles associated with this ResourceProfiles.
func (ms ResourceProfiles) ScopeProfiles() ScopeProfilesSlice {
	// Tree-connected (nested parent): slice shares ms's Handle + indices
	// so cow.Share detach (Phase 5) rebinds the shared tree in place
	// across parent and all derived slice/element wrappers.
	return ScopeProfilesSlice{
		h:     ms.h,
		rpIdx: ms.rpIdx,
	}
}

// SchemaUrl returns the schemaurl associated with this ResourceProfiles.
func (ms ResourceProfiles) SchemaUrl() string {
	return ms.getOrig().SchemaUrl
}

// SetSchemaUrl replaces the schemaurl associated with this ResourceProfiles.
func (ms ResourceProfiles) SetSchemaUrl(v string) {
	ms.getState().DetachIfShared()
	ms.getState().AssertMutable()
	ms.getOrig().SchemaUrl = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ResourceProfiles) CopyTo(dest ResourceProfiles) {
	// Path Y Phase 5 auto-detach prelude — see MoveTo for the doc.
	dest.getState().DetachIfShared()
	dest.getState().AssertMutable()
	internal.CopyResourceProfiles(dest.getOrig(), ms.getOrig())
}

func (ms ResourceProfiles) getOrig() *internal.ResourceProfiles {
	return ms.h.GetOrig().ResourceProfiles[ms.rpIdx]
}

func (ms ResourceProfiles) getState() *internal.State {
	return ms.h.GetState()
}
