// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestKeyValueAndUnit_MoveTo(t *testing.T) {
	ms := generateTestKeyValueAndUnit()
	dest := NewKeyValueAndUnit()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewKeyValueAndUnit().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestKeyValueAndUnit().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestKeyValueAndUnit().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newKeyValueAndUnit(internal.NewKeyValueAndUnit(), sharedState)) })
	assert.Panics(t, func() { newKeyValueAndUnit(internal.NewKeyValueAndUnit(), sharedState).MoveTo(dest) })
}

func TestKeyValueAndUnit_CopyTo(t *testing.T) {
	ms := NewKeyValueAndUnit()
	orig := NewKeyValueAndUnit()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestKeyValueAndUnit()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newKeyValueAndUnit(internal.NewKeyValueAndUnit(), sharedState)) })
}

func TestKeyValueAndUnit_KeyStrindex(t *testing.T) {
	ms := NewKeyValueAndUnit()
	assert.Equal(t, int32(0), ms.KeyStrindex())
	ms.SetKeyStrindex(int32(13))
	assert.Equal(t, int32(13), ms.KeyStrindex())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newKeyValueAndUnit(internal.NewKeyValueAndUnit(), sharedState).SetKeyStrindex(int32(13)) })
}

func TestKeyValueAndUnit_Value(t *testing.T) {
	ms := NewKeyValueAndUnit()
	// Semantic equality (Path Y Phase 4 step 2a): compare *getOrig() rather
	// than the wrapper struct itself. See message_test.go.tmpl for rationale.
	// When the field type lives in a different package (.messageHasWrapper),
	// use the exported internal.Get<X>Orig accessor since getOrig() is
	// package-private. When it lives in the same package, use getOrig()
	// directly.
	assert.Equal(t, *internal.GetValueOrig(internal.ValueWrapper(pcommon.NewValueEmpty())), *internal.GetValueOrig(internal.ValueWrapper(ms.Value())))
	ms.getOrig().Value = *internal.GenTestAnyValue()
	assert.Equal(t, *internal.GetValueOrig(internal.GenTestValueWrapper()), *internal.GetValueOrig(internal.ValueWrapper(ms.Value())))
}

func TestKeyValueAndUnit_UnitStrindex(t *testing.T) {
	ms := NewKeyValueAndUnit()
	assert.Equal(t, int32(0), ms.UnitStrindex())
	ms.SetUnitStrindex(int32(13))
	assert.Equal(t, int32(13), ms.UnitStrindex())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newKeyValueAndUnit(internal.NewKeyValueAndUnit(), sharedState).SetUnitStrindex(int32(13)) })
}

func generateTestKeyValueAndUnit() KeyValueAndUnit {
	return newKeyValueAndUnit(internal.GenTestKeyValueAndUnit(), internal.NewState())
}
