// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestMetrics_MoveTo(t *testing.T) {
	ms := generateTestMetrics()
	dest := NewMetrics()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewMetrics().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestMetrics().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestMetrics().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newMetrics(internal.NewExportMetricsServiceRequest(), sharedState)) })
	assert.Panics(t, func() { newMetrics(internal.NewExportMetricsServiceRequest(), sharedState).MoveTo(dest) })
}

func TestMetrics_CopyTo(t *testing.T) {
	ms := NewMetrics()
	orig := NewMetrics()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestMetrics()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newMetrics(internal.NewExportMetricsServiceRequest(), sharedState)) })
}

func TestMetrics_ResourceMetrics(t *testing.T) {
	ms := NewMetrics()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewResourceMetricsSlice().getOrig(), *ms.ResourceMetrics().getOrig())
	ms.getOrig().ResourceMetrics = internal.GenTestResourceMetricsPtrSlice()
	assert.Equal(t, *generateTestResourceMetricsSlice().getOrig(), *ms.ResourceMetrics().getOrig())
}

func generateTestMetrics() Metrics {
	return newMetrics(internal.GenTestExportMetricsServiceRequest(), internal.NewState())
}
