// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestHistogramDataPoint_MoveTo(t *testing.T) {
	ms := generateTestHistogramDataPoint()
	dest := NewHistogramDataPoint()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewHistogramDataPoint().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestHistogramDataPoint().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestHistogramDataPoint().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newHistogramDataPoint(internal.NewHistogramDataPoint(), sharedState)) })
	assert.Panics(t, func() { newHistogramDataPoint(internal.NewHistogramDataPoint(), sharedState).MoveTo(dest) })
}

func TestHistogramDataPoint_CopyTo(t *testing.T) {
	ms := NewHistogramDataPoint()
	orig := NewHistogramDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestHistogramDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newHistogramDataPoint(internal.NewHistogramDataPoint(), sharedState)) })
}

func TestHistogramDataPoint_Attributes(t *testing.T) {
	ms := NewHistogramDataPoint()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetMapOrig(internal.MapWrapper(pcommon.NewMap())), *internal.GetMapOrig(internal.MapWrapper(ms.Attributes())))
	ms.getOrig().Attributes = internal.GenTestKeyValueSlice()
	assert.Equal(t, *internal.GetMapOrig(internal.GenTestMapWrapper()), *internal.GetMapOrig(internal.MapWrapper(ms.Attributes())))
}

func TestHistogramDataPoint_StartTimestamp(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.StartTimestamp())
	testValStartTimestamp := pcommon.Timestamp(1234567890)
	ms.SetStartTimestamp(testValStartTimestamp)
	assert.Equal(t, testValStartTimestamp, ms.StartTimestamp())
}

func TestHistogramDataPoint_Timestamp(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.Timestamp())
	testValTimestamp := pcommon.Timestamp(1234567890)
	ms.SetTimestamp(testValTimestamp)
	assert.Equal(t, testValTimestamp, ms.Timestamp())
}

func TestHistogramDataPoint_Count(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.Equal(t, uint64(0), ms.Count())
	ms.SetCount(uint64(13))
	assert.Equal(t, uint64(13), ms.Count())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newHistogramDataPoint(internal.NewHistogramDataPoint(), sharedState).SetCount(uint64(13)) })
}

func TestHistogramDataPoint_Sum(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.InDelta(t, float64(0), ms.Sum(), 0.01)
	ms.SetSum(float64(3.1415926))
	assert.True(t, ms.HasSum())
	assert.InDelta(t, float64(3.1415926), ms.Sum(), 0.01)
	ms.RemoveSum()
	assert.False(t, ms.HasSum())
	dest := NewHistogramDataPoint()
	dest.SetSum(float64(3.1415926))
	ms.CopyTo(dest)
	assert.False(t, dest.HasSum())
}

func TestHistogramDataPoint_BucketCounts(t *testing.T) {
	ms := NewHistogramDataPoint()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetUInt64SliceOrig(internal.UInt64SliceWrapper(pcommon.NewUInt64Slice())), *internal.GetUInt64SliceOrig(internal.UInt64SliceWrapper(ms.BucketCounts())))
	ms.getOrig().BucketCounts = internal.GenTestUint64Slice()
	assert.Equal(t, *internal.GetUInt64SliceOrig(internal.GenTestUInt64SliceWrapper()), *internal.GetUInt64SliceOrig(internal.UInt64SliceWrapper(ms.BucketCounts())))
}

func TestHistogramDataPoint_ExplicitBounds(t *testing.T) {
	ms := NewHistogramDataPoint()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetFloat64SliceOrig(internal.Float64SliceWrapper(pcommon.NewFloat64Slice())), *internal.GetFloat64SliceOrig(internal.Float64SliceWrapper(ms.ExplicitBounds())))
	ms.getOrig().ExplicitBounds = internal.GenTestFloat64Slice()
	assert.Equal(t, *internal.GetFloat64SliceOrig(internal.GenTestFloat64SliceWrapper()), *internal.GetFloat64SliceOrig(internal.Float64SliceWrapper(ms.ExplicitBounds())))
}

func TestHistogramDataPoint_Exemplars(t *testing.T) {
	ms := NewHistogramDataPoint()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *NewExemplarSlice().getOrig(), *ms.Exemplars().getOrig())
	ms.getOrig().Exemplars = internal.GenTestExemplarSlice()
	assert.Equal(t, *generateTestExemplarSlice().getOrig(), *ms.Exemplars().getOrig())
}

func TestHistogramDataPoint_Flags(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.Equal(t, DataPointFlags(0), ms.Flags())
	testValFlags := DataPointFlags(1)
	ms.SetFlags(testValFlags)
	assert.Equal(t, testValFlags, ms.Flags())
}

func TestHistogramDataPoint_Min(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.InDelta(t, float64(0), ms.Min(), 0.01)
	ms.SetMin(float64(3.1415926))
	assert.True(t, ms.HasMin())
	assert.InDelta(t, float64(3.1415926), ms.Min(), 0.01)
	ms.RemoveMin()
	assert.False(t, ms.HasMin())
	dest := NewHistogramDataPoint()
	dest.SetMin(float64(3.1415926))
	ms.CopyTo(dest)
	assert.False(t, dest.HasMin())
}

func TestHistogramDataPoint_Max(t *testing.T) {
	ms := NewHistogramDataPoint()
	assert.InDelta(t, float64(0), ms.Max(), 0.01)
	ms.SetMax(float64(3.1415926))
	assert.True(t, ms.HasMax())
	assert.InDelta(t, float64(3.1415926), ms.Max(), 0.01)
	ms.RemoveMax()
	assert.False(t, ms.HasMax())
	dest := NewHistogramDataPoint()
	dest.SetMax(float64(3.1415926))
	ms.CopyTo(dest)
	assert.False(t, dest.HasMax())
}

func generateTestHistogramDataPoint() HistogramDataPoint {
	return newHistogramDataPoint(internal.GenTestHistogramDataPoint(), internal.NewState())
}
