// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// Summary represents the type of a metric that is calculated by aggregating as a Summary of all reported double measurements over a time interval.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewSummary function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Summary struct {
	orig  *internal.Summary
	state *internal.State
}

func newSummary(orig *internal.Summary, state *internal.State) Summary {
	return Summary{orig: orig, state: state}
}

// NewSummary creates a new empty Summary.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewSummary() Summary {
	return newSummary(internal.NewSummary(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Summary) MoveTo(dest Summary) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteSummary(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// DataPoints returns the DataPoints associated with this Summary.
func (ms Summary) DataPoints() SummaryDataPointSlice {
	// Fall-back: ms is either hasWrapper-but-not-top-level (e.g.
	// ProfilesData) or has no nestedPath; either way ms has no Handle
	// to propagate. Use the standalone new<X>Slice constructor — under
	// useHandleLayout it synthesizes a disconnected Handle wrapping
	// orig by pointer, so reads/writes still flow through; cow.Share
	// detach won't propagate into the slice from here (these parents
	// aren't part of the live signal tree).
	return newSummaryDataPointSlice(&ms.getOrig().DataPoints, ms.getState())
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Summary) CopyTo(dest Summary) {
	dest.getState().AssertMutable()
	internal.CopySummary(dest.getOrig(), ms.getOrig())
}

func (ms Summary) getOrig() *internal.Summary {
	return ms.orig
}

func (ms Summary) getState() *internal.State {
	return ms.state
}
