// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// Gauge represents the type of a numeric metric that always exports the "current value" for every data point.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewGauge function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Gauge struct {
	orig  *internal.Gauge
	state *internal.State
}

func newGauge(orig *internal.Gauge, state *internal.State) Gauge {
	return Gauge{orig: orig, state: state}
}

// NewGauge creates a new empty Gauge.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewGauge() Gauge {
	return newGauge(internal.NewGauge(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Gauge) MoveTo(dest Gauge) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteGauge(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// DataPoints returns the DataPoints associated with this Gauge.
func (ms Gauge) DataPoints() NumberDataPointSlice {
	// Fall-back: ms is either hasWrapper-but-not-top-level (e.g.
	// ProfilesData) or has no nestedPath; either way ms has no Handle
	// to propagate. Use the standalone new<X>Slice constructor — under
	// useHandleLayout it synthesizes a disconnected Handle wrapping
	// orig by pointer, so reads/writes still flow through; cow.Share
	// detach won't propagate into the slice from here (these parents
	// aren't part of the live signal tree).
	return newNumberDataPointSlice(&ms.getOrig().DataPoints, ms.getState())
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Gauge) CopyTo(dest Gauge) {
	dest.getState().AssertMutable()
	internal.CopyGauge(dest.getOrig(), ms.getOrig())
}

func (ms Gauge) getOrig() *internal.Gauge {
	return ms.orig
}

func (ms Gauge) getState() *internal.State {
	return ms.state
}
