// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestMetric_MoveTo(t *testing.T) {
	ms := generateTestMetric()
	dest := NewMetric()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewMetric().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestMetric().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestMetric().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newMetric(internal.NewMetric(), sharedState)) })
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).MoveTo(dest) })
}

func TestMetric_CopyTo(t *testing.T) {
	ms := NewMetric()
	orig := NewMetric()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestMetric()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newMetric(internal.NewMetric(), sharedState)) })
}

func TestMetric_Name(t *testing.T) {
	ms := NewMetric()
	assert.Empty(t, ms.Name())
	ms.SetName("test_name")
	assert.Equal(t, "test_name", ms.Name())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetName("test_name") })
}

func TestMetric_Description(t *testing.T) {
	ms := NewMetric()
	assert.Empty(t, ms.Description())
	ms.SetDescription("test_description")
	assert.Equal(t, "test_description", ms.Description())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetDescription("test_description") })
}

func TestMetric_Unit(t *testing.T) {
	ms := NewMetric()
	assert.Empty(t, ms.Unit())
	ms.SetUnit("test_unit")
	assert.Equal(t, "test_unit", ms.Unit())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetUnit("test_unit") })
}

func TestMetric_Type(t *testing.T) {
	tv := NewMetric()
	assert.Equal(t, MetricTypeEmpty, tv.Type())
}

func TestMetric_Gauge(t *testing.T) {
	ms := NewMetric()
	ms.SetEmptyGauge()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	assert.Equal(t, *NewGauge().getOrig(), *ms.Gauge().getOrig())
	ms.getOrig().GetData().(*internal.Metric_Gauge).Gauge = internal.GenTestGauge()
	assert.Equal(t, MetricTypeGauge, ms.Type())
	assert.Equal(t, *generateTestGauge().getOrig(), *ms.Gauge().getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetEmptyGauge() })
}
func TestMetric_Sum(t *testing.T) {
	ms := NewMetric()
	ms.SetEmptySum()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	assert.Equal(t, *NewSum().getOrig(), *ms.Sum().getOrig())
	ms.getOrig().GetData().(*internal.Metric_Sum).Sum = internal.GenTestSum()
	assert.Equal(t, MetricTypeSum, ms.Type())
	assert.Equal(t, *generateTestSum().getOrig(), *ms.Sum().getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetEmptySum() })
}
func TestMetric_Histogram(t *testing.T) {
	ms := NewMetric()
	ms.SetEmptyHistogram()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	assert.Equal(t, *NewHistogram().getOrig(), *ms.Histogram().getOrig())
	ms.getOrig().GetData().(*internal.Metric_Histogram).Histogram = internal.GenTestHistogram()
	assert.Equal(t, MetricTypeHistogram, ms.Type())
	assert.Equal(t, *generateTestHistogram().getOrig(), *ms.Histogram().getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetEmptyHistogram() })
}
func TestMetric_ExponentialHistogram(t *testing.T) {
	ms := NewMetric()
	ms.SetEmptyExponentialHistogram()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	assert.Equal(t, *NewExponentialHistogram().getOrig(), *ms.ExponentialHistogram().getOrig())
	ms.getOrig().GetData().(*internal.Metric_ExponentialHistogram).ExponentialHistogram = internal.GenTestExponentialHistogram()
	assert.Equal(t, MetricTypeExponentialHistogram, ms.Type())
	assert.Equal(t, *generateTestExponentialHistogram().getOrig(), *ms.ExponentialHistogram().getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetEmptyExponentialHistogram() })
}
func TestMetric_Summary(t *testing.T) {
	ms := NewMetric()
	ms.SetEmptySummary()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	assert.Equal(t, *NewSummary().getOrig(), *ms.Summary().getOrig())
	ms.getOrig().GetData().(*internal.Metric_Summary).Summary = internal.GenTestSummary()
	assert.Equal(t, MetricTypeSummary, ms.Type())
	assert.Equal(t, *generateTestSummary().getOrig(), *ms.Summary().getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newMetric(internal.NewMetric(), sharedState).SetEmptySummary() })
}

func TestMetric_Metadata(t *testing.T) {
	ms := NewMetric()
	// Semantic equality (Path Y Phase 4 step 2a) — see message_test.go.tmpl.
	// Cross-package wrappers (elementHasWrapper=pcommon) use internal.Get<X>Orig
	// since getOrig() is package-private.
	assert.Equal(t, *internal.GetMapOrig(internal.MapWrapper(pcommon.NewMap())), *internal.GetMapOrig(internal.MapWrapper(ms.Metadata())))
	ms.getOrig().Metadata = internal.GenTestKeyValueSlice()
	assert.Equal(t, *internal.GetMapOrig(internal.GenTestMapWrapper()), *internal.GetMapOrig(internal.MapWrapper(ms.Metadata())))
}

func generateTestMetric() Metric {
	return newMetric(internal.GenTestMetric(), internal.NewState())
}
