// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofileotlp

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestExportPartialSuccess_MoveTo(t *testing.T) {
	ms := generateTestExportPartialSuccess()
	dest := NewExportPartialSuccess()
	ms.MoveTo(dest)
	// Semantic equality (Path Y Phase 4 step 2a): compare the underlying
	// proto data via *getOrig() rather than the wrapper struct itself.
	// Under the upcoming nested-wrapper Handle layout, two semantically-
	// equal wrappers may carry different Handles + indices and fail
	// reflect.DeepEqual on the struct shape; comparing *getOrig()
	// dereferences to the proto message and gives field-by-field
	// equality that survives the layout change.
	assert.Equal(t, *NewExportPartialSuccess().getOrig(), *ms.getOrig())
	assert.Equal(t, *generateTestExportPartialSuccess().getOrig(), *dest.getOrig())
	dest.MoveTo(dest)
	assert.Equal(t, *generateTestExportPartialSuccess().getOrig(), *dest.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newExportPartialSuccess(internal.NewExportProfilesPartialSuccess(), sharedState)) })
	assert.Panics(t, func() { newExportPartialSuccess(internal.NewExportProfilesPartialSuccess(), sharedState).MoveTo(dest) })
}

func TestExportPartialSuccess_CopyTo(t *testing.T) {
	ms := NewExportPartialSuccess()
	orig := NewExportPartialSuccess()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	orig = generateTestExportPartialSuccess()
	orig.CopyTo(ms)
	assert.Equal(t, *orig.getOrig(), *ms.getOrig())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newExportPartialSuccess(internal.NewExportProfilesPartialSuccess(), sharedState)) })
}

func TestExportPartialSuccess_RejectedProfiles(t *testing.T) {
	ms := NewExportPartialSuccess()
	assert.Equal(t, int64(0), ms.RejectedProfiles())
	ms.SetRejectedProfiles(int64(13))
	assert.Equal(t, int64(13), ms.RejectedProfiles())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newExportPartialSuccess(internal.NewExportProfilesPartialSuccess(), sharedState).SetRejectedProfiles(int64(13))
	})
}

func TestExportPartialSuccess_ErrorMessage(t *testing.T) {
	ms := NewExportPartialSuccess()
	assert.Empty(t, ms.ErrorMessage())
	ms.SetErrorMessage("test_errormessage")
	assert.Equal(t, "test_errormessage", ms.ErrorMessage())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newExportPartialSuccess(internal.NewExportProfilesPartialSuccess(), sharedState).SetErrorMessage("test_errormessage")
	})
}

func generateTestExportPartialSuccess() ExportPartialSuccess {
	return newExportPartialSuccess(internal.GenTestExportProfilesPartialSuccess(), internal.NewState())
}
