// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofileotlp

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// ExportResponse represents the response for gRPC/HTTP client/server.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewExportResponse function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ExportResponse struct {
	orig  *internal.ExportProfilesServiceResponse
	state *internal.State
}

func newExportResponse(orig *internal.ExportProfilesServiceResponse, state *internal.State) ExportResponse {
	return ExportResponse{orig: orig, state: state}
}

// NewExportResponse creates a new empty ExportResponse.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewExportResponse() ExportResponse {
	return newExportResponse(internal.NewExportProfilesServiceResponse(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ExportResponse) MoveTo(dest ExportResponse) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteExportProfilesServiceResponse(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// PartialSuccess returns the partialsuccess associated with this ExportResponse.
func (ms ExportResponse) PartialSuccess() ExportPartialSuccess {
	return newExportPartialSuccess(&ms.getOrig().PartialSuccess, ms.getState())
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ExportResponse) CopyTo(dest ExportResponse) {
	dest.getState().AssertMutable()
	internal.CopyExportProfilesServiceResponse(dest.getOrig(), ms.getOrig())
}

func (ms ExportResponse) getOrig() *internal.ExportProfilesServiceResponse {
	return ms.orig
}

func (ms ExportResponse) getState() *internal.State {
	return ms.state
}
